### PR TITLE
Bug Fix: Fix Side-By-Side Bookings

### LINKED ISSUE #16: Bug - Can't create bookings next to eachother
Testing the API, I can create a booking at a time e.g. 14:30 -> 15:30 but then an internal server error occurs when trying then to book the same position from 15:30 -> 16:30.

```
{
  "errors": [
    {
      "debugMessage": "An unknown error occurred.",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createBooking"
      ],
      "trace": [
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php",
          "line": 347,
          "call": "App\\Booking::App\\{closure}(instance of App\\Booking)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php",
          "line": 196,
          "call": "Illuminate\\Events\\Dispatcher::Illuminate\\Events\\{closure}('eloquent.creating: App\\Booking', array(1))"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php",
          "line": 169,
          "call": "Illuminate\\Events\\Dispatcher::dispatch('eloquent.creating: App\\Booking', array(1), true)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasEvents.php",
          "line": 188,
          "call": "Illuminate\\Events\\Dispatcher::until('eloquent.creating: App\\Booking', instance of App\\Booking)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
          "line": 787,
          "call": "Illuminate\\Database\\Eloquent\\Model::fireModelEvent('creating')"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php",
          "line": 667,
          "call": "Illuminate\\Database\\Eloquent\\Model::performInsert(instance of Illuminate\\Database\\Eloquent\\Builder)"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/Execution/MutationExecutor.php",
          "line": 214,
          "call": "Illuminate\\Database\\Eloquent\\Model::save()"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/Execution/MutationExecutor.php",
          "line": 49,
          "call": "Nuwave\\Lighthouse\\Execution\\MutationExecutor::saveModelWithPotentialParent(instance of App\\Booking, instance of Illuminate\\Support\\Collection(4), null)"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/Schema/Directives/CreateDirective.php",
          "line": 72,
          "call": "Nuwave\\Lighthouse\\Execution\\MutationExecutor::executeCreate(instance of App\\Booking, instance of Illuminate\\Support\\Collection(4))"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php",
          "line": 29,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\CreateDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(instance of Illuminate\\Database\\MySqlConnection)"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/Schema/Directives/CreateDirective.php",
          "line": 76,
          "call": "Illuminate\\Database\\Connection::transaction(instance of Closure)"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/Schema/Factories/FieldFactory.php",
          "line": 222,
          "call": "Nuwave\\Lighthouse\\Schema\\Directives\\CreateDirective::Nuwave\\Lighthouse\\Schema\\Directives\\{closure}(null, array(4), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 632,
          "call": "Nuwave\\Lighthouse\\Schema\\Factories\\FieldFactory::Nuwave\\Lighthouse\\Schema\\Factories\\{closure}(null, array(4), instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 555,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, null, instance of Nuwave\\Lighthouse\\Schema\\Context, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 478,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: Mutation, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 921,
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'createBooking')"
        },
        {
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'createBooking')"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 923,
          "function": "array_reduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 494,
          "call": "GraphQL\\Executor\\ReferenceExecutor::promiseReduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 256,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFieldsSerially(GraphQLType: Mutation, null, array(0), instance of ArrayObject(1))"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 208,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeOperation(instance of GraphQL\\Language\\AST\\OperationDefinitionNode, null)"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 155,
          "call": "GraphQL\\Executor\\ReferenceExecutor::doExecute()"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 158,
          "call": "GraphQL\\Executor\\Executor::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null)"
        },
        {
          "file": "/app/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 90,
          "call": "GraphQL\\GraphQL::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Type\\Schema, 'mutation {\n  createBooking(user_id: 1300005, position: {connect: 1}, from: \"2018-12-24 13:30:00\", to: \"2018-12-24 14:30:00\") {\n    position {\n      name\n    }\n  }\n}', null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null, array(29))"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/GraphQL.php",
          "line": 170,
          "call": "GraphQL\\GraphQL::executeQuery(instance of GraphQL\\Type\\Schema, 'mutation {\n  createBooking(user_id: 1300005, position: {connect: 1}, from: \"2018-12-24 13:30:00\", to: \"2018-12-24 14:30:00\") {\n    position {\n      name\n    }\n  }\n}', null, instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null, array(29))"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/GraphQL.php",
          "line": 109,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeQuery('mutation {\n  createBooking(user_id: 1300005, position: {connect: 1}, from: \"2018-12-24 13:30:00\", to: \"2018-12-24 14:30:00\") {\n    position {\n      name\n    }\n  }\n}', instance of Nuwave\\Lighthouse\\Schema\\Context, array(0), null, null)"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/Support/Http/Controllers/GraphQLController.php",
          "line": 70,
          "call": "Nuwave\\Lighthouse\\GraphQL::executeRequest(instance of Nuwave\\Lighthouse\\Execution\\LighthouseRequest)"
        },
        {
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController::query(instance of Nuwave\\Lighthouse\\Execution\\LighthouseRequest)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Controller.php",
          "line": 54,
          "function": "call_user_func_array(array(2), array(1))"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php",
          "line": 45,
          "call": "Illuminate\\Routing\\Controller::callAction('query', array(1))"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 219,
          "call": "Illuminate\\Routing\\ControllerDispatcher::dispatch(instance of Illuminate\\Routing\\Route, instance of Nuwave\\Lighthouse\\Support\\Http\\Controllers\\GraphQLController, 'query')"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Route.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Route::runController()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 680,
          "call": "Illuminate\\Routing\\Route::run()"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 130,
          "call": "Illuminate\\Routing\\Router::Illuminate\\Routing\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/vendor/nuwave/lighthouse/src/Support/Http/Middleware/AcceptJson.php",
          "line": 30,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Nuwave\\Lighthouse\\Support\\Http\\Middleware\\AcceptJson::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 105,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 682,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 657,
          "call": "Illuminate\\Routing\\Router::runRouteWithinStack(instance of Illuminate\\Routing\\Route, instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 623,
          "call": "Illuminate\\Routing\\Router::runRoute(instance of Illuminate\\Http\\Request, instance of Illuminate\\Routing\\Route)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
          "line": 612,
          "call": "Illuminate\\Routing\\Router::dispatchToRoute(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 176,
          "call": "Illuminate\\Routing\\Router::dispatch(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 130,
          "call": "Illuminate\\Foundation\\Http\\Kernel::Illuminate\\Foundation\\Http\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
          "line": 21,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
          "line": 27,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
          "line": 62,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/app/vendor/fideloper/proxy/src/TrustProxies.php",
          "line": 57,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 171,
          "call": "Fideloper\\Proxy\\TrustProxies::handle(instance of Illuminate\\Http\\Request, instance of Closure)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
          "line": 105,
          "call": "Illuminate\\Pipeline\\Pipeline::Illuminate\\Pipeline\\{closure}(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 151,
          "call": "Illuminate\\Pipeline\\Pipeline::then(instance of Closure)"
        },
        {
          "file": "/app/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
          "line": 116,
          "call": "Illuminate\\Foundation\\Http\\Kernel::sendRequestThroughRouter(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/public/index.php",
          "line": 55,
          "call": "Illuminate\\Foundation\\Http\\Kernel::handle(instance of Illuminate\\Http\\Request)"
        },
        {
          "file": "/app/server.php",
          "line": 21,
          "function": "require_once('/app/public/index.php')"
        }
      ]
    }
  ]
}```

### PR DESCRIPTION
**Pull request by atoff**
Not really a bug, just a side effect of not making the Exception readable.

Closes #16

### CODE REVIEW

File: tests/Feature/Booking/BookingTest.php [hunk 1]
```diff
@@ -260,6 +277,89 @@ public function testInvalidBookingCantBeCreated()
         );
     }
 
+    /** @test */
+    public function testOverlappingBookings()
```
Comment (AxonC) [inline tests/Feature/Booking/BookingTest.php:281]: Can you split this test up?

Comment (atoff) [reply tests/Feature/Booking/BookingTest.php:281]: Not sure it would be beneficial, would just have to create the test bookings & positions every time

File: app/Booking.php [hunk 2]
```diff
@@ -9,37 +9,52 @@
...
     {
         return $this->belongsTo(Position::class);
     }
 
-    public static function canBeMade($position_id, $from, $to)
+    public static function canBeMade($position_id, $from, $to, $excludeID = null)
     {
-        return !self::where('position_id', $position_id)
-            ->where(function ($query) use ($from, $to) {
+        $query = self::where('position_id', $position_id);
```
Comment (AxonC) [inline app/Booking.php:22]: It could be worth only pulling the bookings of a position for the day of the intended booking otherwise this gets intense real quick.

File: app/Booking.php [hunk 3]
```diff
@@ -9,37 +9,52 @@
...
-        self::creating(function ($booking) {
+        self::creating(function (self $booking) {
             if (!self::canBeMade($booking->position_id, $booking->from, $booking->to)) {
                 throw new OverlappingBookingException();
             }
         });
+
+        self::updating(function (self $booking) {
+            if (!self::canBeMade($booking->position_id, $booking->from, $booking->to, $booking->id)) {
+                throw new OverlappingBookingException();
```
Comment (AxonC) [inline app/Booking.php:56]: Instead of throwing this on the model event, would it not be better placed in a service class?

**Review by AxonC — CHANGES_REQUESTED** [review]

**Comment by AxonC** [comment]
**QA**

Tests run: https://vatsim-uk.testquality.com/project/9057/plan/15441/run/121983/result/1668961

Result: **PASS**

File: app/Booking.php (hunk 3 above)
Comment (atoff) [reply app/Booking.php:56]: I originally tried this using a custom resolver in GraphQL, but believe me this is the far simpler implementation (and more catch-all imo)

**Review by AxonC — APPROVED** [review]
